language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: Z88MsIJmP5S98y6XTMXz7pB9bAsMPyN/V0IeIKchGOXxnO9v1sVzVKm994/CnpO6PNWWTUW8xUIl3A1uWV4E4hJfEqgI7IFO74AVQY02A0oiJkvrV9phVti4eO4+hr8FlM5DywhvebC7KPTOLMuNCwNVbH6ykKXpN8WiIQ3YYtg=
  - secure: G7BiTVYDKGcwD2tRrLTa8lAQqDEWtldNPodihCG/hhXiPfIqXAX6zsVtbU1A6UW2/GBEj9DRuUlfDaFJFEWI0/uxc8YdhKSpwk+BibmhVBVJ8AS1PiKHfF3Kb8r7pj0ShhhuLStB1csQv4+oI0UXJWFhDrJe1wn0acl0IKo94nw=
  - secure: Ya/qYA8HfzYwfgigqTpqfmmncLdJDs3GCUWF2oIhCYBwidZjFmDG36S6znl4g42hCMs9ZXEqElTJReVLxDtno3d9vWgpxhm8p/X93QTUArDSUwbbLBTcn636B4sMvzjtt+aODdxWHvGcaD5ZjDXuOWbKcqPoLcI0YrcoYvqj/Yw=
